$ErrorActionPreference = 'Stop'

$repoRoot = Split-Path -Parent $PSScriptRoot
$buildDir = Join-Path $repoRoot 'build\windows-x64\Debug'
$packageRoot = Join-Path $repoRoot 'dist\physics-sim-release'

$repoRootFull = [System.IO.Path]::GetFullPath($repoRoot)
$packageRootFull = [System.IO.Path]::GetFullPath($packageRoot)
if (-not $packageRootFull.StartsWith($repoRootFull, [System.StringComparison]::OrdinalIgnoreCase))
{
    throw "Refusing to delete or recreate a package outside the repository root: $packageRootFull"
}

& (Join-Path $PSScriptRoot 'build.ps1')

if (Test-Path -LiteralPath $packageRoot)
{
    Remove-Item -LiteralPath $packageRoot -Recurse -Force
}

New-Item -ItemType Directory -Path $packageRoot -Force | Out-Null

$exe = Join-Path $buildDir 'physics-sim.exe'
if (-not (Test-Path -LiteralPath $exe))
{
    throw "Missing build output: $exe"
}

Copy-Item -LiteralPath $exe -Destination $packageRoot

Get-ChildItem -LiteralPath $buildDir -Filter '*.dll' -File | ForEach-Object {
    Copy-Item -LiteralPath $_.FullName -Destination $packageRoot
}

$packageScenes = Join-Path $packageRoot 'scenes'
New-Item -ItemType Directory -Path $packageScenes -Force | Out-Null

Get-ChildItem -LiteralPath (Join-Path $repoRoot 'scenes') -Filter '*.pscene' -File | ForEach-Object {
    Copy-Item -LiteralPath $_.FullName -Destination $packageScenes
}

Copy-Item -LiteralPath (Join-Path $repoRoot 'README.md') -Destination $packageRoot

$manifestPath = Join-Path $packageRoot 'package-manifest.txt'
$manifestLines = @(
    'Physics Sim release package manifest',
    'Generated by scripts\package-release.ps1',
    ''
)

Get-ChildItem -LiteralPath $packageRoot -Recurse -File |
    Where-Object { $_.Name -ne 'package-manifest.txt' } |
    Sort-Object FullName |
    ForEach-Object {
        $relativePath = $_.FullName.Substring($packageRootFull.Length + 1)
        $hash = (Get-FileHash -Algorithm SHA256 -LiteralPath $_.FullName).Hash
        $manifestLines += ("{0} | {1}" -f $relativePath, $hash)
    }

Set-Content -LiteralPath $manifestPath -Value $manifestLines

$requiredFiles = @(
    'physics-sim.exe',
    'README.md',
    'package-manifest.txt',
    'scenes\starter_basin.pscene',
    'scenes\demo_scene.pscene'
)

foreach ($requiredFile in $requiredFiles)
{
    $requiredPath = Join-Path $packageRoot $requiredFile
    if (-not (Test-Path -LiteralPath $requiredPath))
    {
        throw "Package is missing required file: $requiredFile"
    }
}

Write-Host "[release-package] created $packageRoot"
Get-Content -LiteralPath $manifestPath
